In [2]:
# 1. 0으로 채워진 크기가 20인 배열을 생성하세요.
import numpy as np

a1=np.zeros(20, dtype='int')
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
# 2. 0부터 15까지의 값을 갖는 4 x 4 행렬을 생성하세요.
a2=np.arange(16).reshape((4,4))
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [7]:
# 3. 길이가 10인데 세번째 요소만 1이고, 나머지 요소는 0인 배열을 생성하세요.
a3=np.zeros(10, dtype='int')
a3[2]=1

a3

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0])

In [9]:
# 4. 1에서 10까지의 값을 갖는 배열을 생성하세요.
a4=np.arange(1,11)
a4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
# 5. 위의 배열의 순서를 거꾸로 바꿔주세요.
a5=a4[::-1]
a5

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [14]:
# 6. 4x4 단위행렬을 만드세요. (단위 행렬(영어: identity matrix)은 주대각선의 원소가 모두 1이며 나머지 원소는 모두 0인 정사각 행렬이다.)
a6=np.eye(4)
a6

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
# 7. 랜덤한 값을 가지는 3X3X3 배열을 생성하세요.
a7=np.random.rand(3,3,3)
a7

array([[[0.75548171, 0.07938331, 0.98195268],
        [0.90978513, 0.16966386, 0.58462608],
        [0.45878323, 0.83321422, 0.43000642]],

       [[0.92263001, 0.49179948, 0.73659086],
        [0.75095544, 0.90760289, 0.67898863],
        [0.45771811, 0.07819766, 0.69284273]],

       [[0.00339121, 0.99720329, 0.38379966],
        [0.86375511, 0.32559446, 0.61678873],
        [0.71269647, 0.4416428 , 0.00758388]]])

In [17]:
# 8. 위에서 생성한 배열 원소의 최대값, 최솟값을 구하세요.
[a7.max(), a7.min()]

[0.9972032925496018, 0.0033912147373844626]

In [18]:
# 8. 20개의 랜덤한 값을 가진 배열을 생성하고, 그 배열의 평균값을 구하시오.
#참고: numpy에서 평균을 구하는 함수 - mean()
a8=np.random.rand(20)
a8.mean()

0.5497495830175925

In [31]:
#9. 4x4 의 2차원 배열을 생성하세요. 단 테두리는 1을 내부는 0으로 채워주세요.
a9=np.zeros((4,4))
a9[0]=1
a9[-1]=1
a9[1,0]=1
a9[1,-1]=1
a9[2,0]=1
a9[2,-1]=1
a9

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])